import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <div className="flex-1">
          {children}
        </div>
        <footer className="text-center py-8 text-sm text-[var(--text-muted)] border-t border-[var(--border)] mt-auto">
          <div className="flex justify-center gap-6">
            <a href="/privacy" className="hover:text-[var(--text-primary)] transition-colors">Privacy Policy</a>
            <a href="/terms" className="hover:text-[var(--text-primary)] transition-colors">Terms of Service</a>
          </div>
        </footer>
      </body>
    </html>
  );
}
